name: Build and Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t flask-app:latest .

    - name: Save image to tar file
      run: docker save flask-app:latest -o flask-app.tar

    - name: Copy image to remote server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "flask-app.tar"
        target: "~/"

    - name: Deploy and run image on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker load -i flask-app.tar
          docker stop flask-container || true
          docker rm flask-container || true
          docker run -d --name flask-container -p 80:5000 flask-app:latest
